/**
 * Supabase Client Configuration
 * 
 * This file exports two Supabase clients:
 * 1. Client-side client (safe to use in browser)
 * 2. Server-side client (with service role key for admin operations)
 */

import { createClient } from '@supabase/supabase-js';

// Validate environment variables
const supabaseUrl = process.env.NEXT_PUBLIC_SUPABASE_URL;
const supabasePublishableKey = process.env.NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY;

if (!supabaseUrl) {
    throw new Error('Missing NEXT_PUBLIC_SUPABASE_URL environment variable');
}

if (!supabasePublishableKey) {
    throw new Error('Missing NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY environment variable');
}

/**
 * Client-side Supabase client
 * Safe to use in browser, respects RLS policies
 */
export const supabase = createClient(supabaseUrl, supabasePublishableKey);

/**
 * Server-side Supabase client (Admin)
 * Only use in API routes or server components
 * Bypasses RLS policies - use with caution!
 */
export const getServerSupabase = () => {
    const supabaseSecretKey = process.env.SUPABASE_SECRET_KEY;

    if (!supabaseSecretKey) {
        throw new Error('Missing SUPABASE_SECRET_KEY environment variable');
    }

    return createClient(supabaseUrl, supabaseSecretKey, {
        auth: {
            autoRefreshToken: false,
            persistSession: false
        }
    });
};

/**
 * Database Types
 * These will be auto-generated by Supabase CLI in the future
 * For now, we'll define them manually
 */

export interface Cutoff {
    id: number;
    institute: string;
    program: string;
    stream: string;
    quota: string;
    category: string;
    seat_type: string;
    round: string;
    year: number;
    opening_rank: number;
    closing_rank: number;
    sr_no: number | null;
    created_at: string;
    updated_at: string;
}

export interface UserWishlist {
    id: number;
    user_id: string;
    cutoff_id: number;
    notes: string | null;
    created_at: string;
}
