import { createClient } from '@supabase/supabase-js';
import { config } from 'dotenv';
import fs from 'fs';
import { FETCH_BATCH_SIZE, TABLES } from '../build/config';

config({ path: '.env.local', quiet: true });

const supabase = createClient(
    process.env.NEXT_PUBLIC_SUPABASE_URL!,
    process.env.SUPABASE_SECRET_KEY!
);

interface CutoffRecord {
    institute: string;
    [key: string]: unknown;
}

async function compareColleges() {
    console.log('📥 Fetching data from Supabase...');

    // Fetch data from Supabase
    let data: CutoffRecord[] = [];
    let from = 0;

    while (true) {
        const { data: chunk, error } = await supabase
            .from(TABLES.CUTOFFS)
            .select('institute')
            .range(from, from + FETCH_BATCH_SIZE - 1);

        if (error) {
            console.error('❌ Error fetching data:', error);
            process.exit(1);
        }

        if (!chunk || chunk.length === 0) break;

        data = data.concat(chunk);
        process.stdout.write(`\r   Fetched ${data.length} records...`);
        from += FETCH_BATCH_SIZE;

        if (chunk.length < FETCH_BATCH_SIZE) break;
    }
    process.stdout.write('\n\n');

    // Read mobile-index.json (generated by build:mobile)
    const indexPath = './public/data/mobile-index.json';

    if (!fs.existsSync(indexPath)) {
        console.error('❌ mobile-index.json not found!');
        console.error('   Run: npm run build:mobile');
        console.error('   This will generate the index file.\n');
        process.exit(1);
    }

    const mobileIndex = JSON.parse(fs.readFileSync(indexPath, 'utf8'));

    // Extract unique institutes from Supabase data
    const dataColleges = [...new Set(data.map(r => r.institute))].sort();

    // Get colleges from mobile index
    const indexColleges = mobileIndex.colleges.sort();

    console.log('\n' + '='.repeat(70));
    console.log('INSTITUTE COUNT INVESTIGATION');
    console.log('='.repeat(70));

    console.log(`\nSupabase: ${dataColleges.length} colleges`);
    console.log(`mobile-index.json: ${indexColleges.length} colleges`);
    console.log(`Difference: ${indexColleges.length - dataColleges.length} colleges\n`);

    // Find colleges in mobile index but NOT in Supabase data
    const extraInIndex = indexColleges.filter((c: string) => !dataColleges.includes(c));

    console.log(`Extra colleges in MOBILE INDEX (not in Supabase): ${extraInIndex.length}`);
    console.log('-'.repeat(70));
    extraInIndex.forEach((c: string, i: number) => {
        console.log(`${(i + 1).toString().padStart(3)}. ${c}`);
    });

    // Find colleges in Supabase but NOT in mobile index
    const missingInIndex = dataColleges.filter((c: string) => !indexColleges.includes(c));

    if (missingInIndex.length > 0) {
        console.log(`\nColleges in SUPABASE but MISSING from mobile index: ${missingInIndex.length}`);
        console.log('-'.repeat(70));
        missingInIndex.forEach((c: string, i: number) => {
            console.log(`${(i + 1).toString().padStart(3)}. ${c}`);
        });
    } else {
        console.log(`\n✅ All Supabase colleges are present in mobile index!`);
    }

    console.log('\n' + '='.repeat(70));
}

compareColleges().catch(console.error);
